### ISSUE TITLE
Fatal error: when loading a fresh copy of QWcrm - add a graceful fail

### ISSUE THREAD

**Issue by shoulders** [shoulders/qwcrm#579]
The tables are not created so this is pre-install

````
Fatal error: Uncaught exception 'ADODB_Exception' with message 'mysqli error: [1146: Table 'xxxxxxx_qwcrm.yekl_version' doesn't exist] in EXECUTE("SELECT * FROM yekl_version ORDER BY yekl_version.database_version DESC LIMIT 1")' in /home/xxxxxxx/public_html/qwcrm/libraries/adodb/adodb-exceptions.inc.php:80 Stack trace: #0 /home/xxxxxxx/public_html/qwcrm/libraries/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'xxxxxxx...', 'SELECT * FROM y...', false, Object(ADODB_mysqli)) #1 /home/xxxxxxx/public_html/qwcrm/libraries/adodb/adodb.inc.php(1240): ADOConnection->_Execute('SELECT * FROM y...', false) #2 /home/xxxxxxx/public_html/qwcrm/includes/include.php(48): ADOConnection->Execute('SELECT * FROM y...') #3 /home/xxxxxxx/public_html/qwcrm/includes/include.php(675): get_qwcrm_database_version_number(Object(ADODB_mysqli)) #4 /home/xxxxxxx/public_html/qwcrm/index.php(183): verify_qwcrm_is_installed_correctly(Object(ADODB_mysqli)) #5 {main} thrown in /home/xxxxxxx/public_html/qwcrm/libraries/adodb/adodb-exceptions.inc.php on line 80
````

**Comment by shoulders** [comment]
this was caused by me leaving a configuration.php inplace after deleting the database from a prior trail

**Comment by shoulders** [comment]
perhaps add some code so the failure is recognised, i will not be the first nor the last

**Comment by shoulders** [comment]
this is caused by the configuration.php file being present but no version number (or database) tables present in the database.

**Comment by shoulders** [comment]
add some error checking on to get_qwcrm_database_version_number()
